name: "Main action file of composite actions"
description: "composite actions"

inputs:
  GITHUB_TOKEN:
    description: "Token used to access repo"
    required: false
  owner:
    description: owner
    default: ${{ github.event.repository.owner.login }}
    required: false 
  repo:
    description: repo
    default: ${{ github.event.repository.name }}
    required: false 
  base:
    description: base uri
    default: "https://api.github.com"
    required: false  
  head_ref:  
    description: Head Refer branch
    default: ${{ contains(github.head_ref, 'release') }}
    required: false
  base_ref:
    description: Base Refer branch
    default: ${{ contains(github.base_ref, 'master') }}
    required: false   
    
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/main.sh
      shell: bash
      env:
        REPO_OWNER: ${{ inputs.owner }}
        REPO_NAME: ${{ inputs.repo }}
        BASE_URI: ${{ inputs.base }}
        head_ref: ${{ inputs.head_ref }}
        base_ref: ${{ inputs.base_ref }}