name: GitHub CLI Action

inputs:
  GITHUB_TOKEN:
    description: "Token used to access repo"
    required: false


runs:
  using: "composite"
  steps:
    - run: sh ./makeDraft.sh ${{ github.event.pull_request.number }}
      shell: bash
    