name: 'Merge and close PR using slash-commands'
on: 
  issue_comment:

permissions: write-all
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.issue.number }} 
  REPO_NAME: ${{ github.repository }}
  
jobs:
  Merge_and_Close-PR:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge and close PR
        uses: ./