name: Testing secretes

on:
  push:
    

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  EVENT: ${{ github.event.action }} 
  WEBHOOK: "https://chat.googleapis.com/v1/spaces/AAAAE1j9nuM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=3kBsnjcv9kTsSS8c0c_jQMR8fNt8ccdC-O-8iIGEl6s"

 
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Google Chat Integration
        run: echo ${{ secrets.GITHUB_TOKEN }}
